package bbw.fcoi.bad;

import java.util.UUID;

public abstract class Car {
	// The Chassis number is not chosen by the user, but generated by the system, and cannot be changed.
	private final UUID chassisNumber = UUID.randomUUID();
	private int drivenKilometers;

	public int getDrivenKilometers() {
		return drivenKilometers;
	}

	public void incrementDrivenKilometers() {
		this.drivenKilometers++;
	}

	public UUID getChassisNumber() {
		return chassisNumber;
	}

	public abstract void start();
}
