package bbw.fcoi.good;

import java.util.UUID;

public class Car {
	// The Chassis number is not chosen by the user, but generated by the system, and cannot be changed.
	private final UUID chassisNumber = UUID.randomUUID();
	private int drivenKilometers;
	private IEngine engine;

	/**
	 * Just like a real car, a car needs an engine to start.
	 * Since there are different types of engines, we use an interface to abstract it, which makes it interchangeable.
	 * Now, if a new type of engine was introduced, we could just implement the IEngine interface and pass it to
	 * the car, without having to change existing code.
	 * @param engine The engine that the car uses.
	 */
	public Car(IEngine engine) {
		this.engine = engine;
	}

	public void start() {
		engine.start();
	}

	public void setEngine(IEngine engine) {
		this.engine = engine;
	}

	public int getDrivenKilometers() {
		return drivenKilometers;
	}

	public void incrementDrivenKilometers() {
		this.drivenKilometers++;
	}

	public UUID getChassisNumber() {
		return chassisNumber;
	}
}
